apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80          # Porta do serviço dentro do cluster
      targetPort: 8000  # Porta do container onde o app está escutando
      nodePort: 30001   # Porta exposta no nó do Kubernetes (acesso externo)
